DROP TABLE IF EXISTS `HEALTH_PROFILE` cascade ;
DROP TABLE IF EXISTS `HEALTH_METRIC` cascade ;

CREATE TABLE IF NOT EXISTS `HEALTH_PROFILE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS `HEALTH_METRIC` (
   `ID` INT NOT NULL AUTO_INCREMENT,
   `VALUE` DOUBLE NOT NULL,
   `TYPE` VARCHAR(45) NOT NULL,
   `PROFILE_ID` INT NOT NULL,
   PRIMARY KEY (`ID`));